modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="bluecitizen"
version="1.18.2"
displayName="MPProject BlueCitizen"
logoFile="examplemod.png"
credits="MPProject BlueCitizen Core Mod"
authors="MPProject"
description='''
MPProject BlueCitizen Core Mod
'''

[[dependencies.bluecitizen]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bluecitizen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"